# Generated by Django 5.2.15 on 2026-06-18 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_tag', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('LAPTOP', 'Laptop'), ('DESKTOP', 'Desktop'), ('PRINTER', 'Printer'), ('NETWORK', 'Network Device'), ('PHONE', 'Phone'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('IN_REPAIR', 'In Repair'), ('SPARE', 'Spare'), ('RETIRED', 'Retired'), ('LOST', 'Lost')], default='ACTIVE', max_length=20)),
                ('serial_number', models.CharField(blank=True, max_length=80)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('warranty_expiry', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['asset_tag'],
            },
        ),
    ]
